name: Deploy To EKS

on:
  # allow manual runs (for reruns)
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to deploy (e.g. 123). If blank and triggered by CI, will use workflow_run.run_number'
        required: false
  # automatic when CI-CD workflow completes
  workflow_run:
    workflows: ["vprofile actions"]
    types: 
      - completed

env:
  AWS_REGION: us-east-1
  ECR_REPO_APP: vprofileapp
  ECR_REPO_DB: vprofiledb
  EKS_CLUSTER: kitops-eks

jobs:
  DeployToEKS:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Kube config file
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER }}

      - name: Print config file
        run: cat ~/.kube/config

      - name: Create namespace if not exists
        run: |
           kubectl create namespace vprofile --dry-run=client -o yaml | kubectl apply -f -

      - name: Create or update regcred
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=${{ secrets.REGISTRY }} \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password) \
            -n vprofile \
            --dry-run=client -o yaml | kubectl apply -f -
            
      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.EKS_CLUSTER }}
          #config-files: .github/values/dev.yaml
          chart-path: ./kubedefAMZAI/vprofile-app
          namespace: vprofile
          values: "app.image.repository=${{ secrets.REGISTRY }}/${{ env.ECR_REPO_APP }},app.image.tag=latest,database.image.repository=${{ secrets.REGISTRY }}/${{ env.ECR_REPO_DB }},database.image.tag=latest,database.persistence.storageClass=gp2"

          name: vprofile-stack
